name: Bingo
version: 1.0-SNAPSHOT
main: fr.bingo.BingoPlugin
api-version: 1.21
authors: [Antigravity]
description: Un plugin reproduisant le mode de jeu Bingo.

commands:
  bingo:
    description: Commande principale du Bingo
    aliases: [b]
  bg:
    description: Ouvrir la grille de Bingo
  bs:
    description: Alias pour bingo size
  tj:
    description: Alias pour team join
  team:
    description: Gestion des équipes
  party:
    description: Commande pour lancer ou mettre en pause la partie
    permission: bingo.admin
  pregen:
    description: Pré-générer les chunks
    permission: bingo.admin
