name: Bingo
version: 1.0-SNAPSHOT
main: fr.bingo.BingoPlugin
api-version: 1.21
authors: [Antigravity]
description: Un plugin reproduisant le mode de jeu Bingo.
load: STARTUP

commands:
  bingo:
    description: Commande principale du Bingo
    aliases: [b]
  bg:
    description: Ouvrir la grille de Bingo
  bs:
    description: Alias pour bingo size
  tj:
    description: Alias pour team join
  team:
    description: Gestion des equipes
  pregen:
    description: Pre-generer les chunks
    permission: bingo.admin
  c:
    description: Recevoir le compas de configuration admin
    permission: bingo.admin
  ff:
    description: Voter pour abandonner la partie
  game:
    description: Voir les reglages de la partie
    aliases: [info]
