name: HEL
version: 1.6.0
main: fr.hel.HelPlugin
api-version: 1.21
authors: [Antigravity]
description: Plugin UHC multijoueur avec scenarios modulaires (Hel, UHC Run, etc.)
load: STARTUP
softdepend: [WorldEdit]

commands:
  bingo:
    description: Commande principale du Hel
    aliases: [b]
  bg:
    description: Ouvrir la grille de Hel
  bs:
    description: Alias pour bingo size
  tj:
    description: Alias pour team join
  parkour:
    description: Commencer le jump
    aliases: [jump]
  team:
    description: Gestion des equipes
  pregen:
    description: Pre-generer les chunks
    permission: bingo.admin
  c:
    description: Recevoir le compas de configuration admin
    permission: bingo.admin
  ff:
    description: Voter pour abandonner la partie
  game:
    description: Voir les reglages de la partie
    aliases: [info]
  finish:
    description: Sauvegarde l'inventaire de depart en mode edition.
    permission: bingo.admin
  setrank:
    description: Definir le grade d'un joueur
    permission: bingo.admin
  nick:
    description: Changer de pseudo
    permission: bingo.admin
